### ISSUE TITLE
Onlap relations

### ISSUE THREAD

**Issue by domist07** [gempy-project/gempy#564] opened 2020-12-23 10:06 UTC
I try to build a model with Onlap relations, but the cutting of the surfaces isn't as I expect. Here is the picture what GemPy produces:
![2020-12-23 10_59_59-PyVista](https://user-images.githubusercontent.com/59735059/102984578-1474f500-450e-11eb-86e5-aaf740b2b424.png)
However, according to my imagination, the blue surface should be present as the top layer in the center of the model. There the blue data points are above those of the red layer.

 I set the series and their relation with:
```python
gp.map_stack_to_surfaces(geo_model,
                         {"b": 'blue',
                          "r": 'red',
                          "y": 'yellow',
                          "g": 'green',
                          "ba": 'basement'},
                         remove_unused_series=True)

geo_model.series._w.set_bottom_relation(["b", "r", "y", "g", "ba"],
                                        ["Onlap", "Onlap", "Onlap", "Onlap", "Onlap"])
```

**Desktop**
  * OS: Windows10
  * GemPy Version 2.2.6
  * Spyder 4.2.0

**Comment by AlexanderJuestel** [comment] 2021-01-27 07:42
Hey @domist07,

sorry for the late reply over a month later! Have you been able to find a solution for your issue already? If not I am trying to ping @Leguark to help you out here.

Cheers Alex

**Comment by domist07** [comment] 2021-01-27 17:26
Unfortunately no. Shall I send you the data for replication?

**Comment by Leguark** [comment] 2021-02-04 13:31
Hey @domist07 sorry for being absent for a month, we had a pressing deadline last week. Mmmm could be due to the order of the series? I always get very confused with what is the expected behavior when we start mixing erodes and onlap :smile: 

If the order is not the case just create a test here https://github.com/cgre-aachen/gempy/blob/master/test/test_community_bugs/test_community_bugs.py and make a pull request

**Comment by Leguark** [comment] 2021-02-05 14:44
Okay I just made a new release and in principle, it should be fixed just take a look. It still looks weird because there is blue volume on top of the blue and red surface but I think it is the right behaviour.

Also, usually is not a good idea to use restricted methods. Use better:
```
geo_model.set_bottom_relation(["b", "r", "y", "g", "ba"],
                                        ["Onlap", "Onlap", "Onlap", "Onlap", "Onlap"])
```

Cheers!

**Comment by domist07** [comment] 2021-02-10 10:40
Thanks @Leguark for the update. Now it looks much better!
However, I noticed that if I increase the radius to 200m the result on the northern side still looks weird 🤔
In my opinion, all layers there should be masked by the green one, so that the purple volume covers the whole width.
![grafik](https://user-images.githubusercontent.com/59735059/107498693-6b08c200-6b94-11eb-986d-a182656ff0ce.png)

**Comment by AlexanderJuestel** [comment] 2021-09-07 13:58
Is this still an open issue @domist07? Otherwise feel free to close the issue :)

**Comment by Japhiolite** [comment] 2022-05-04 09:44
What's the status on this issue? @domist07 can we close this?

**Closed** 2024-04-16 11:42 UTC
Labels: question, bug?
