### ISSUE TITLE
Version requirement

### ISSUE THREAD

**Issue by KodalAnwesha** [gempy-project/gempy#913] opened 2024-06-25 06:17 UTC
**What is your question?**
Which version of Pyvista and vtk is required to generate 3D model in GemPy?

**Comment by javoha** [comment] 2024-06-25 07:28
Hello,
did you face any problems with the most recent versions (vtk=9.3.0, pyvista=0.43,10)? It works for me with the setup we discussed in #912.
Cheers
Jan

**Comment by KodalAnwesha** [comment] 2024-06-25 07:35
Hi, 
I guess it is working, because there is no error showing. But the PyVista window is not opening. 
Thanks

**Comment by KodalAnwesha** [comment] 2024-06-25 10:14
Hi,
Could you please help me out. The 3D models are not generating. Only the 2D sections are visible.

**Comment by KodalAnwesha** [comment] 2024-06-25 10:39
I have used this code in different cell still the pyvista window is not opening.

gpv.plot_3d(geo_model, kwargs_plot_structured_grid={'opacity': .2})

**Comment by Leguark** [comment] 2024-06-25 11:25
Is PyVista otherwise working? Can you try to plot a sphere?

miguel@DESKTOP-L0T7RJ5:~$ source .virtualenvs/gempy_2024.2.0/bin/activate
(gempy_2024.2.0) miguel@DESKTOP-L0T7RJ5:~$ python
Python 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista
>>> pyvista.Sphere().plot()

**Comment by KodalAnwesha** [comment] 2024-06-25 13:39
Yes, it is working.

**Comment by KodalAnwesha** [comment] 2024-06-26 05:41
Hi, 
Could you please help me out regarding the problem I mentioned. As you have said, the pyvista is working otherwise, like plotting the sphere. But it is not working with GemPy. The pyvista window is not coming.

**Comment by javoha** [comment] 2024-06-26 06:50
What happens if you set `image=True` in `gpv.plot_3d` as a keyword?

**Comment by KodalAnwesha** [comment] 2024-06-26 07:00
Like for example, while running this code,
gpv.plot_3d(geo_model, show_surfaces=True, image=True)
The 3D model is coming in the jupyter notebook itself, not in the pyvista window. I want it in the pyvista window, so that I can orient the 3D model in my own way. Is it the problem of pyvista or my system?

**Comment by javoha** [comment] 2024-06-26 07:15
Mmh ok I am not sure why this is not working. Which example are you using? And what IDE are you in? Does not necessarily seem to be a gempy issue to be honest.

**Comment by Leguark** [comment] 2024-06-26 07:22
Unfortunately, we are unable to reproduce the issue on our end, so we will be closing this issue for now.

To help us assist you more effectively in the future, please follow the reporting guidelines (pasted below). Additionally, please be aware that most GemPy contributors volunteer their time, so responses should not be expected immediate. For professional support options, please refer to the sponsoring section.

-------------

**Describe the bug**
A clear and concise description of what the bug is. Include error messages / 
tracebacks. If useful include screenshots.

**To Reproduce**
Provide detailed steps to reproduce the behavior:

1.
2.
3.
...

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
  * OS: (e.g. iOS)
  * GemPy Version
    * if installed via pip: provide GemPy version (e.g. 2.0.1)
    * if cloned from GitHub: provide Git commit id (e.g. 839bf85f)
  * Jupyter Version (if applicable)

**Additional context**
Add any other context about the problem here.

**Closed by Leguark** 2024-06-26 07:22 UTC
